
title: DPG Midwest Document Cloud
domain: dpgmidwest.org/document-cloud
baseurl: "https://www.dpgmidwest.org/document-cloud/"
logo: "images/logo-dark-shadow-line.png"
language: "English"

# Search Engine Optimization and Metatag Information
seo-title: DPG Midwest Document Cloud
seo-description: Document Cloud
seo-keywords: ""
favicon: "images/favicons/favicon.ico"
thumbnail: "images/logo-dark-shadow-line.png"
theme-color: "#000000"
locale: en_US
adsbot-policy: noindex
card-type: website
card-social-type: summary

# Schema
schema-type: Organization

# Plugins and Jekyll technical stuff
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: [jekyll-paginate, jekyll-seo-tag]
anchorjs: false
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
permalink: pretty

# Pagination
paginate: 10
paginate_path: "/:num/"

# Links and socials
email: "midwestdualpower@protonmail.com"
github_repo: dpgmidwest.github.io
github_name: dpgmidwest
instagram: dualpowergatheringmidwest
mastodon_name: dpgmidwest
mastodon_server: kolektiva.social